export const CONTEXT_ACCESSOR_HEADER = `
/**
 * CONTEXT ENTITY RESOLVER IS FOR USE WITH CUSTOM FIELD RESOLVER
 * ENTITY WILL BE RESOLVED FROM CONTEXT ENTITY RESOLVER WITH PROVIDED FUNCTION
 * IMPORT CUSTOM FIELD RESOLVER FROM PACKAGE
 * import { FieldResolver } from "@adgstudio/graphql-generator"
 */
`.trim();
