export const FIELD_RESOLVER_HEADER = `
/**
 * FIELD RESOLVER ARRANGEMENT OF ARGUMENTS (SOURCE, ARGS, CONTEXT, INFO) IS FOR USE WITH CUSTOM FIELD RESOLVER
 * DEFAULT ONE ONLY INCLUDES (ARGS, CONTEXT, INFO) IN THE ARGUMENTS
 * IMPORT THE CUSTOM FIELD RESOLVER FROM PACKAGE
 * import { FieldResolver } from "@adgstudio/graphql-generator"
 */
`.trim();
