name: MAIN

on:
  push:
    branches:
      - main

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: cache node_modules
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          path: |
            ./node_modules
      - name: install latest npm
        run: |
          ([ ! -d ./node_modules ] && npm install -g npm || echo "CACHE ALREADY EXISTS") &&
          echo "CURRENT NPM VERSION ($(npm -v)) NODE ($(node -v))" &&
          echo "PATHS NPM ($(which npm)) NODE ($(which node))"
      - name: install dependencies
        env:
          TEST: "TEST ENV"
        run: |
          ([ ! -d ./node_modules ] && npm ci || echo "CACHE ALREADY EXISTS") &&
          echo "ENV ($TEST)"

  lint:
    needs:
      - install_dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: restore node_modules cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          path: |
            ./node_modules
      - name: lint (CHECK FOR WARNINGS ✋)
        run: ./node_modules/.bin/npm run lint:all

  tests:
    needs:
      - install_dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: restore node_modules cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          path: |
            ./node_modules
      - name: run tests
        run: ./node_modules/.bin/npm run test:ci

  build:
    needs:
      - install_dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: restore node_modules cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          path: |
            ./node_modules
      - name: build
        run: |
          ./node_modules/.bin/npm run build &&
          cd ./dist/ && ls -a

  release:
    needs:
      - install_dependencies
      - lint
      - tests
      - build
    runs-on: ubuntu-latest
    environment:
      name: RELEASE
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: restore node_modules cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          path: |
            ./node_modules
      - name: configure git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com" &&
          git config --global user.name "GitHub Actions"
      - name: create release
        env:
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        run: |
          npm run release
      - name: publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        run: |
          npm publish --access public
      - name: push tags
        run: |
          git push --follow-tags origin ${{ GITHUB.GITHUB_REF_NAME }}
      - name: merge with dev
        env:
          BRANCHES: dev
          MERGE_WITH: ${{ GITHUB.REF_NAME }}
        run: |
          bash ./.scripts/git-merge-branch.sh &&
          git push --all origin

  prerelease:
    needs:
      - install_dependencies
      - lint
      - tests
      - build
    runs-on: ubuntu-latest
    environment:
      name: PRERELEASE
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: restore node_modules cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          path: |
            ./node_modules
      - name: configure git
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com" &&
          git config --global user.name "GitHub Actions"
      - name: create prerelease
        env:
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        run: |
          npm run prerelease
      - name: publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
        run: |
          npm publish --access public --tag next
      - name: push tags
        run: |
          git push --follow-tags origin ${{ GITHUB.GITHUB_REF_NAME }}
